### ISSUE TITLE
Problem Expo.io version

### ISSUE THREAD

**Issue by Angelk90** [sonnylazuardi/react-native-nike-running#4]
@sonnylazuardi : I wanted to try the version at the following link:
https://expo.io/@sonnylazuardi/nike-plus-running

But it does not work.
Expo version installed on the device, last.

**Comment by jleei** [comment]
same problem.

**Comment by trihargianto** [comment]
yeah, same problem too :disappointed:

**Comment by sonnylazuardi** [comment]
i moved the expo project to snack https://snack.expo.io/@sonnylazuardi/nike-running-redesign cheers 😄

**Comment by Angelk90** [comment]
@sonnylazuardi :  Does not work.
![](https://i.imgur.com/E0Bq52B.jpg)
