### ISSUE TITLE
How to setup and build native iOS and Android projects?

### ISSUE THREAD

**Issue by forconz** [sonnylazuardi/react-native-nike-running#5]
Clone the repo
$ git clone https://github.com/sonnylazuardi/react-native-nike-running.git
Cloning into 'react-native-nike-running'...
remote: Counting objects: 109, done.
Receiving objectremote: Total 109 (delta 0), reused 0 (delta 0), pack-reused 10
Receiving objects: 100% (109/109), 385.02 KiB | 46.00 KiB/s, done.
Resolving deltas: 100% (37/37), done.

$ cd react-native-nike-running

Install dependencies (npm v3+):
$ npm install
Running on iOS:
$ react-native run-ios

In a separate terminal window run:
$ react-native start

is it ok?

https://expo.io/@sonnylazuardi/nike-plus-running
Is it an empty new project?
How to get started with Expo?
exp start
Preview your project
Open Expo Client on your device. Use it to scan the QR code printed by exp start. You may have to wait a minute while your project bundles and loads for the first time.

But How to find the QR code for nike-plus-running project?

**Comment by sonnylazuardi** [comment]
I just updated to use native ios and android project (without expo) please pull and checkit out 💯
